// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sumera_Travel_Corporation.Models
{
    [Table(nameof(Airport), Schema = "MasterData")]
    public  class Airport
    {

        [Key]
        public int AirportId { get; set; }
       
        [StringLength(50)]
       
        public string AirportName { get; set; }
        public int AirportCode { get; set; }
       
        [StringLength(50)]
       
        public string Address1 { get; set; }
      
        [StringLength(50)]
        
        public string Address2 { get; set; }
     
        [StringLength(50)]
      
        public string Address3 { get; set; }
       
        public int PinCode { get; set; }
        public long Telephone1 { get; set; }
        public long Telephone2 { get; set; }
     
        [StringLength(50)]
       
        public string Email1 { get; set; }
      
        [StringLength(50)]
   
        public string Email2 { get; set; }

        public int CityRefId { get; set; }
        [ForeignKey("CityRefId")]
        
        public  City city { get; set; }
  
       
    }
}