// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sumera_Travel_Corporation.Models
{
    [Table(nameof(Amenity), Schema = "MasterData")]
    public partial class Amenity
    {
       

        [Key]
        public int AmenitiesId { get; set; }
      
        [StringLength(50)]
   
        public string AmenitiesName { get; set; }
    
        [StringLength(100)]
   
        public string AmenitiesDescription { get; set; }

      
    }
}