// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sumera_Travel_Corporation.Models
{
    [Table(nameof(City), Schema = "MasterData")]
    public  class City
    {
    

        [Key]
        public int CityId { get; set; }
     
        [StringLength(50)]
     
        public string CityName { get; set; }
        public int CountryRefId { get; set; }
        [ForeignKey("CountryRefId")]
        public  Country country { get; set; }
     
        
        
    }
}