// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sumera_Travel_Corporation.Models
{
    [Table(nameof(Country), Schema = "MasterData")]
    public  class Country
    {
       

        [Key]
        public int CountryId { get; set; }
        public int CountryCode { get; set; }
       
        [StringLength(50)]
      
        public string CountryName { get; set; }

        
    }
}