// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sumera_Travel_Corporation.Models
{

    [Table(nameof(Customer), Schema = "MasterData")]
    public partial class Customer
    {
        [Key]
        public int CustomerId { get; set; }
       
        [StringLength(50)]
       
        public string CustomerFirstName { get; set; }
    
        [StringLength(50)]
       
        public string CustomerLastName { get; set; }
      
        public DateTime DateOfBirth { get; set; }
       
        [StringLength(50)]
       
        public string Address1 { get; set; }
     
        [StringLength(50)]
   
        public string Address2 { get; set; }
        
        [StringLength(50)]
       
        public string Address3 { get; set; }
      
        public int PinCode { get; set; }
        public long Telephone1 { get; set; }
       
        [StringLength(50)]
      
        public string Email1 { get; set; }

        public int CityRefId { get; set; }
        [ForeignKey("CityRefId")]
        public  City city { get; set; }
    }
}