// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Sumera_Travel_Corporation.Models
{
    [Table(nameof(HotelAmenitiesLink), Schema = "MasterData")]
    public  class HotelAmenitiesLink
    {
        [Key]
        public int HotelAmenitiesLinkId { get; set; }
        public int HotelRefId { get; set; }
        [ForeignKey("HotelRefId")]

        public  Hotel hotel { get; set; }
        public int AmenitiesRefId { get; set; }

        [ForeignKey("AmenitiesRefId")]
      
        public  Amenity amenities { get; set; }
      
    }
}