// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sumera_Travel_Corporation.Data;

#nullable disable

namespace Sumera_Travel_Corporation.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sumera_Travel_Corporation.Data.Models.HolidayBooking", b =>
                {
                    b.Property<int>("HolidayBookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayBookingId"), 1L, 1);

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("HolidayPackageId")
                        .HasColumnType("int");

                    b.HasKey("HolidayBookingId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("HolidayPackageId");

                    b.ToTable("HolidayBooking", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Data.Models.HolidayPackage", b =>
                {
                    b.Property<int>("HolidayPackageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HolidayPackageId"), 1L, 1);

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Duration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("HolidayPackagePrice")
                        .HasColumnType("int");

                    b.Property<int>("HotelrefId")
                        .HasColumnType("int");

                    b.Property<int>("NumberofGuest")
                        .HasColumnType("int");

                    b.Property<string>("PackageTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("from_locationRefId")
                        .HasColumnType("int");

                    b.Property<int>("to_locationRefId")
                        .HasColumnType("int");

                    b.HasKey("HolidayPackageId");

                    b.HasIndex("HotelrefId");

                    b.HasIndex("from_locationRefId");

                    b.HasIndex("to_locationRefId");

                    b.ToTable("HolidayPackage", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Data.Models.Locations", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"), 1L, 1);

                    b.Property<string>("LocationName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Airline", b =>
                {
                    b.Property<int>("AirlineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirlineId"), 1L, 1);

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("AirlineName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CityRefId")
                        .HasColumnType("int");

                    b.Property<string>("Email1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<long>("Telephone1")
                        .HasColumnType("bigint");

                    b.Property<long>("Telephone2")
                        .HasColumnType("bigint");

                    b.HasKey("AirlineId");

                    b.HasIndex("CityRefId");

                    b.ToTable("Airline", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Airport", b =>
                {
                    b.Property<int>("AirportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AirportId"), 1L, 1);

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AirportCode")
                        .HasColumnType("int");

                    b.Property<string>("AirportName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CityRefId")
                        .HasColumnType("int");

                    b.Property<string>("Email1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<long>("Telephone1")
                        .HasColumnType("bigint");

                    b.Property<long>("Telephone2")
                        .HasColumnType("bigint");

                    b.HasKey("AirportId");

                    b.HasIndex("CityRefId");

                    b.ToTable("Airport", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Amenity", b =>
                {
                    b.Property<int>("AmenitiesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AmenitiesId"), 1L, 1);

                    b.Property<string>("AmenitiesDescription")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("AmenitiesName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AmenitiesId");

                    b.ToTable("Amenity", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.City", b =>
                {
                    b.Property<int>("CityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CityId"), 1L, 1);

                    b.Property<string>("CityName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CountryRefId")
                        .HasColumnType("int");

                    b.HasKey("CityId");

                    b.HasIndex("CountryRefId");

                    b.ToTable("City", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"), 1L, 1);

                    b.Property<int>("CountryCode")
                        .HasColumnType("int");

                    b.Property<string>("CountryName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CountryId");

                    b.ToTable("Country", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"), 1L, 1);

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address3")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CityRefId")
                        .HasColumnType("int");

                    b.Property<string>("CustomerFirstName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CustomerLastName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<long>("Telephone1")
                        .HasColumnType("bigint");

                    b.HasKey("CustomerId");

                    b.HasIndex("CityRefId");

                    b.ToTable("Customer", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Flight", b =>
                {
                    b.Property<int>("FlightId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlightId"), 1L, 1);

                    b.Property<string>("Address1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Address2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("AirlineRefId")
                        .HasColumnType("int");

                    b.Property<int>("CityRefId")
                        .HasColumnType("int");

                    b.Property<string>("Email1")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Email2")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FlightCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("FromAirportRefId")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PinCode")
                        .HasColumnType("int");

                    b.Property<long>("Telephone1")
                        .HasColumnType("bigint");

                    b.Property<long>("Telephone2")
                        .HasColumnType("bigint");

                    b.Property<int>("ToAirportRefId")
                        .HasColumnType("int");

                    b.HasKey("FlightId");

                    b.HasIndex("AirlineRefId");

                    b.HasIndex("CityRefId");

                    b.HasIndex("FromAirportRefId");

                    b.HasIndex("ToAirportRefId");

                    b.ToTable("Flight", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Hotel", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelId"), 1L, 1);

                    b.Property<int>("CityRefId")
                        .HasColumnType("int");

                    b.Property<string>("HotelAdress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HotelName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("HotelRent")
                        .HasColumnType("int");

                    b.Property<string>("Stars")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelId");

                    b.HasIndex("CityRefId");

                    b.ToTable("Hotel", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.HotelAmenitiesLink", b =>
                {
                    b.Property<int>("HotelAmenitiesLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelAmenitiesLinkId"), 1L, 1);

                    b.Property<int>("AmenitiesRefId")
                        .HasColumnType("int");

                    b.Property<int>("HotelRefId")
                        .HasColumnType("int");

                    b.HasKey("HotelAmenitiesLinkId");

                    b.HasIndex("AmenitiesRefId");

                    b.HasIndex("HotelRefId");

                    b.ToTable("HotelAmenitiesLink", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.State", b =>
                {
                    b.Property<int>("StateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StateId"), 1L, 1);

                    b.Property<int>("CountryRefId")
                        .HasColumnType("int");

                    b.Property<string>("StateName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("StateId");

                    b.HasIndex("CountryRefId");

                    b.ToTable("State", "MasterData");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Data.Models.HolidayBooking", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sumera_Travel_Corporation.Data.Models.HolidayPackage", "HolidayPackage")
                        .WithMany()
                        .HasForeignKey("HolidayPackageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HolidayPackage");

                    b.Navigation("customer");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Data.Models.HolidayPackage", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.Hotel", "hotel")
                        .WithMany()
                        .HasForeignKey("HotelrefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sumera_Travel_Corporation.Data.Models.Locations", "fromlocation")
                        .WithMany()
                        .HasForeignKey("from_locationRefId");

                    b.HasOne("Sumera_Travel_Corporation.Data.Models.Locations", "tolocation")
                        .WithMany()
                        .HasForeignKey("to_locationRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fromlocation");

                    b.Navigation("hotel");

                    b.Navigation("tolocation");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Airline", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.City", "city")
                        .WithMany()
                        .HasForeignKey("CityRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Airport", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.City", "city")
                        .WithMany()
                        .HasForeignKey("CityRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.City", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.Country", "country")
                        .WithMany()
                        .HasForeignKey("CountryRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Customer", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.City", "city")
                        .WithMany()
                        .HasForeignKey("CityRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Flight", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.Airline", "airline")
                        .WithMany()
                        .HasForeignKey("AirlineRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sumera_Travel_Corporation.Models.City", "city")
                        .WithMany()
                        .HasForeignKey("CityRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sumera_Travel_Corporation.Models.Airport", "fromAirport")
                        .WithMany()
                        .HasForeignKey("FromAirportRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sumera_Travel_Corporation.Models.Airport", "toAirport")
                        .WithMany()
                        .HasForeignKey("ToAirportRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("airline");

                    b.Navigation("city");

                    b.Navigation("fromAirport");

                    b.Navigation("toAirport");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.Hotel", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.City", "city")
                        .WithMany()
                        .HasForeignKey("CityRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("city");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.HotelAmenitiesLink", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.Amenity", "amenities")
                        .WithMany()
                        .HasForeignKey("AmenitiesRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sumera_Travel_Corporation.Models.Hotel", "hotel")
                        .WithMany()
                        .HasForeignKey("HotelRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("amenities");

                    b.Navigation("hotel");
                });

            modelBuilder.Entity("Sumera_Travel_Corporation.Models.State", b =>
                {
                    b.HasOne("Sumera_Travel_Corporation.Models.Country", "country")
                        .WithMany()
                        .HasForeignKey("CountryRefId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("country");
                });
#pragma warning restore 612, 618
        }
    }
}
